;;; Ex. 1.14

;;; Draw the tree illustrating the process generated by the count-change
;;; procedure of section 1.2.2 in making change for 11 cents. What are the
;;; orders of growth of the space and number of steps used by this process as
;;; the amount to be changed increases?

;;; (cc 1 5)
;;; Steps: 11
;;; Space: 6

;;; (cc 2 5)
;;; Steps: 13
;;; Space: 7

;;; Steps increases by roughly 2n or O(n)
;;; Space increases by roughly n or O(n)
